### ISSUE TITLE
setup_as_lan_device can make LAN device inaccessible

### ISSUE THREAD

**Issue by wwahammy** [qca/boardfarm#45]
A LAN device in boardfarm has two network connections: one connected to the DUT (eth1) and one connected to the outside network (eth0). Additionally, when a LAN device is set up as part of starting a bft test, [setup_as_lan_device](https://github.com/qca/boardfarm/blob/master/devices/debian.py#L223-L247) in debian.py is run. One of the commands taken by setup_as_lan_device is to kill all of the dhclient processes on the computer. This makes sense for the dhclient for eth1 to put DUT system in a clean state. This however can cause issues if eth0 is managed via dhcp. Eventually the eth0 dhcp lease will expire. Since the dhclient process for handling eth0 has been killed in setup_as_lan_device however, the lease will not be renewed and the LAN device will become, at the very least, somewhat inaccessible. The best way to handle this now is, if you can get access to the LAN device, run `dhclient -v eth0` or `reboot` or simply power-cycle the device.

setup_as_lan_device should be modified so that dhclient for eth1 can be killed without affecting the eth0 dhclient. This isn't necessarily straightforward though. For example, if the program `dhclient` was run without any arguments, then a single dhclient process manages all of the dhcp managed interfaces. This means that to kill the dhclient for eth1, we need to kill the dhclient for eth0. If we do that, or just `killall dhclient` like we do now, we need to run `dhclient -v eth0`. That might work but I'm not sure what happens if we run `dhclient -v eth0` if eth0 is managed statically. Does it cause any issues?

**Comment by mbanders** [comment]
There are a few ways to achieve this, but here is is the result you need.

The routing table on the lan-side device needs to look like this:

```
root@vm-07:~# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    0      0        0 eth1
10.0.0.0        10.0.0.1        255.0.0.0       UG    0      0        0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U     0      0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     0      0        0 eth1
```

The first line is called the "default route" and you can see it goes through `eth1` to the router-under-test at `192.168.1.1`.

The second line, starting with `10.0.0.0`, goes through `eth0` to your primary router at `10.0.0.1` (or whatever it is for you).  This route is what makes it possible to ssh to the lan-side device via `eth0`, no matter how badly you might mess up `eth1` or the router-under-test.

So that's what you need it to look like.

You have some options, here' is one way.  For our setups, we set `eth0` to a static IP address by adding these lines to `/etc/network/interfaces`:

```
iface eth0 inet static
  address 10.0.0.73
  up route add -net 10.0.0.0 netmask 255.0.0.0 gw 10.0.0.1
```

With that entry, the lan-side device will always have the same IP address, and the needed route is added to the routing table.

Here's another way: if you don't like static IP addresses, *_maybe *_ this will work:

```
iface eth0 inet dhcp
  up route add -net 10.0.0.0 netmask 255.0.0.0 gw 10.0.0.1
```

Personally we like using static IP addresses, because then it's one less variable that can change.

**Comment by wwahammy** [comment]
I guess the decisions to go with static makes sense. Right now, I have a static dhcp lease for eth0 so I can connect to eth0 using its IP address even after the lease expiration. The router providing dhcp and dns doesn't think the hostname is valid though after the lease expired so I can't connect to eth0 via the hostname. It's not a huge issue for me, I can handle that a couple of different ways.

At some point, I think it'd be good to have support for eth0 to staying connected well via DHCP since that's a pretty common setup for average folks. I guess I'll keep this on the back burner as a nice to have feature :)

**Comment by mattsm** [comment]
I fixed this in https://github.com/qca/boardfarm/commit/e80b73d9ed2d91294b4b16cbbed8a862280f816b
