### ISSUE TITLE
Purpose of Test "CheckQosScripts"? 

### ISSUE THREAD

**Issue by yi-liang** [qca/boardfarm#68]
Looks like the Test "CheckQosScripts" is checking if "qos-scripts" was **not** installed,
what was the purpose of this test? should it run before some other tests to make sure "qos-scripts" was not installed?

**Comment by mbanders** [comment]
There were some people who made some openwrt builds that wanted to make sure qos-scripts package was not installed because it interfered with some things they cared about.

Feel free to remove that from your own test suite, you probably don't need it.  You can add or remove whatever tests you want by changing testsuites.cfg: https://github.com/qca/boardfarm/blob/master/testsuites.cfg

**Comment by yi-liang** [comment]
Thanks, @mbanders
